name: Mondays 02:00 UTC
on:
  schedule:
    - cron: "0 2 * * 1"
jobs:
  weekly-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger build Pipeline
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-pipeline.yml/dispatches \
               -d '{"ref":"main"}'